// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/sunr3d/order-stream-processor/models"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, orderUID
func (_m *Cache) Get(ctx context.Context, orderUID string) (*models.Order, error) {
	ret := _m.Called(ctx, orderUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Order, error)); ok {
		return rf(ctx, orderUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Order); ok {
		r0 = rf(ctx, orderUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Cache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUID string
func (_e *Cache_Expecter) Get(ctx interface{}, orderUID interface{}) *Cache_Get_Call {
	return &Cache_Get_Call{Call: _e.mock.On("Get", ctx, orderUID)}
}

func (_c *Cache_Get_Call) Run(run func(ctx context.Context, orderUID string)) *Cache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cache_Get_Call) Return(_a0 *models.Order, _a1 error) *Cache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cache_Get_Call) RunAndReturn(run func(context.Context, string) (*models.Order, error)) *Cache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, orders
func (_m *Cache) Restore(ctx context.Context, orders []*models.Order) error {
	ret := _m.Called(ctx, orders)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Order) error); ok {
		r0 = rf(ctx, orders)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cache_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type Cache_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - orders []*models.Order
func (_e *Cache_Expecter) Restore(ctx interface{}, orders interface{}) *Cache_Restore_Call {
	return &Cache_Restore_Call{Call: _e.mock.On("Restore", ctx, orders)}
}

func (_c *Cache_Restore_Call) Run(run func(ctx context.Context, orders []*models.Order)) *Cache_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.Order))
	})
	return _c
}

func (_c *Cache_Restore_Call) Return(_a0 error) *Cache_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cache_Restore_Call) RunAndReturn(run func(context.Context, []*models.Order) error) *Cache_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, orderUID, order
func (_m *Cache) Set(ctx context.Context, orderUID string, order *models.Order) error {
	ret := _m.Called(ctx, orderUID, order)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Order) error); ok {
		r0 = rf(ctx, orderUID, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Cache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUID string
//   - order *models.Order
func (_e *Cache_Expecter) Set(ctx interface{}, orderUID interface{}, order interface{}) *Cache_Set_Call {
	return &Cache_Set_Call{Call: _e.mock.On("Set", ctx, orderUID, order)}
}

func (_c *Cache_Set_Call) Run(run func(ctx context.Context, orderUID string, order *models.Order)) *Cache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.Order))
	})
	return _c
}

func (_c *Cache_Set_Call) Return(_a0 error) *Cache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cache_Set_Call) RunAndReturn(run func(context.Context, string, *models.Order) error) *Cache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
