// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/sunr3d/order-stream-processor/models"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// GetAllOrders provides a mock function with given fields: ctx
func (_m *OrderService) GetAllOrders(ctx context.Context) ([]*models.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []*models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type OrderService_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderService_Expecter) GetAllOrders(ctx interface{}) *OrderService_GetAllOrders_Call {
	return &OrderService_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx)}
}

func (_c *OrderService_GetAllOrders_Call) Run(run func(ctx context.Context)) *OrderService_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderService_GetAllOrders_Call) Return(_a0 []*models.Order, _a1 error) *OrderService_GetAllOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetAllOrders_Call) RunAndReturn(run func(context.Context) ([]*models.Order, error)) *OrderService_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, orderUID
func (_m *OrderService) GetOrder(ctx context.Context, orderUID string) (*models.Order, error) {
	ret := _m.Called(ctx, orderUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Order, error)); ok {
		return rf(ctx, orderUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Order); ok {
		r0 = rf(ctx, orderUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUID string
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, orderUID interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderUID)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, orderUID string)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(_a0 *models.Order, _a1 error) *OrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*models.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) ProcessOrder(ctx context.Context, order *models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for ProcessOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_ProcessOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessOrder'
type OrderService_ProcessOrder_Call struct {
	*mock.Call
}

// ProcessOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *models.Order
func (_e *OrderService_Expecter) ProcessOrder(ctx interface{}, order interface{}) *OrderService_ProcessOrder_Call {
	return &OrderService_ProcessOrder_Call{Call: _e.mock.On("ProcessOrder", ctx, order)}
}

func (_c *OrderService_ProcessOrder_Call) Run(run func(ctx context.Context, order *models.Order)) *OrderService_ProcessOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *OrderService_ProcessOrder_Call) Return(_a0 error) *OrderService_ProcessOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_ProcessOrder_Call) RunAndReturn(run func(context.Context, *models.Order) error) *OrderService_ProcessOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
