// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/sunr3d/order-stream-processor/models"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, order
func (_m *Database) Create(ctx context.Context, order *models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Database_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *models.Order
func (_e *Database_Expecter) Create(ctx interface{}, order interface{}) *Database_Create_Call {
	return &Database_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *Database_Create_Call) Run(run func(ctx context.Context, order *models.Order)) *Database_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *Database_Create_Call) Return(_a0 error) *Database_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_Create_Call) RunAndReturn(run func(context.Context, *models.Order) error) *Database_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, orderUID
func (_m *Database) Read(ctx context.Context, orderUID string) (*models.Order, error) {
	ret := _m.Called(ctx, orderUID)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Order, error)); ok {
		return rf(ctx, orderUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Order); ok {
		r0 = rf(ctx, orderUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type Database_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUID string
func (_e *Database_Expecter) Read(ctx interface{}, orderUID interface{}) *Database_Read_Call {
	return &Database_Read_Call{Call: _e.mock.On("Read", ctx, orderUID)}
}

func (_c *Database_Read_Call) Run(run func(ctx context.Context, orderUID string)) *Database_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Database_Read_Call) Return(_a0 *models.Order, _a1 error) *Database_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_Read_Call) RunAndReturn(run func(context.Context, string) (*models.Order, error)) *Database_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAll provides a mock function with given fields: ctx
func (_m *Database) ReadAll(ctx context.Context) ([]*models.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadAll")
	}

	var r0 []*models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_ReadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAll'
type Database_ReadAll_Call struct {
	*mock.Call
}

// ReadAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Database_Expecter) ReadAll(ctx interface{}) *Database_ReadAll_Call {
	return &Database_ReadAll_Call{Call: _e.mock.On("ReadAll", ctx)}
}

func (_c *Database_ReadAll_Call) Run(run func(ctx context.Context)) *Database_ReadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Database_ReadAll_Call) Return(_a0 []*models.Order, _a1 error) *Database_ReadAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_ReadAll_Call) RunAndReturn(run func(context.Context) ([]*models.Order, error)) *Database_ReadAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
