// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Broker is an autogenerated mock type for the Broker type
type Broker struct {
	mock.Mock
}

type Broker_Expecter struct {
	mock *mock.Mock
}

func (_m *Broker) EXPECT() *Broker_Expecter {
	return &Broker_Expecter{mock: &_m.Mock}
}

// StartConsumer provides a mock function with given fields: ctx, handler
func (_m *Broker) StartConsumer(ctx context.Context, handler func(context.Context, []byte) error) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for StartConsumer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, []byte) error) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Broker_StartConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartConsumer'
type Broker_StartConsumer_Call struct {
	*mock.Call
}

// StartConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(context.Context , []byte) error
func (_e *Broker_Expecter) StartConsumer(ctx interface{}, handler interface{}) *Broker_StartConsumer_Call {
	return &Broker_StartConsumer_Call{Call: _e.mock.On("StartConsumer", ctx, handler)}
}

func (_c *Broker_StartConsumer_Call) Run(run func(ctx context.Context, handler func(context.Context, []byte) error)) *Broker_StartConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, []byte) error))
	})
	return _c
}

func (_c *Broker_StartConsumer_Call) Return(_a0 error) *Broker_StartConsumer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Broker_StartConsumer_Call) RunAndReturn(run func(context.Context, func(context.Context, []byte) error) error) *Broker_StartConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroker creates a new instance of Broker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Broker {
	mock := &Broker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
